const ERROR_TITLES = {
  VALIDATION_ERROR: "Validation Error",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Not Found",
  DEFAULT: "An error occurred",
};

const ERROR_CODE_TO_ERROR_TITLE_MAP = {
  400: ERROR_TITLES.VALIDATION_ERROR,
  401: ERROR_TITLES.UNAUTHORIZED,
  402: ERROR_TITLES.FORBIDDEN,
  403: ERROR_TITLES.NOT_FOUND,
};

export { ERROR_CODE_TO_ERROR_TITLE_MAP, ERROR_TITLES };
